#!/usr/bin/env python3
"""Emit docs/security_metrics.tex from the deterministic security artifacts.

Same discipline as frozen_metrics.tex: every security numeral in the prose is a
generated macro bound to results/, so a re-run can never leave a stale number in
the manuscript (the numeric-drift class E1/E7 from the 2026-08-15 plan).
"""
import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
sec = json.loads((ROOT / "results" / "security_evaluation.json").read_text())
corp = json.loads((ROOT / "results" / "corpus_evaluation.json").read_text())

V = sec["vectors"]
S = V["summary"]
INS = sec["semantic_inspection"]
WF = sec["wire_fuzzing"]
NC = sec["negative_controls"]["false_block"]

def name(sub):
    return next(k for k in S if sub.lower() in k.lower())

evi, comp = S["eviassure"], S[name("Composed")]
tuf, dsse, opa, ci = S[name("TUF")], S[name("DSSE")], S[name("OPA")], S[name("status gate")]
ov = [c for c in INS["per_class"] if c["anomaly_class"].startswith("ANOMALY")]
st = [c for c in INS["per_class"] if c["anomaly_class"].startswith("STEALTH")]

def rate(m, k):
    return [(f"{k}Blocked", m["k"]), (f"{k}Total", m["n"]),
            (f"{k}Pct", f"{m['rate_pct']:.1f}"),
            (f"{k}CIlo", f"{m['ci95_low_pct']:.1f}"), (f"{k}CIhi", f"{m['ci95_high_pct']:.1f}")]

rows = []
for m, k in ((evi, "evi"), (comp, "comp"), (tuf, "tuf"), (dsse, "dsse"), (opa, "opa"), (ci, "cigate")):
    rows += rate(m, k)
rows += [
    ("scoredVectors", V["n_scored_vectors"]),
    ("eviUnblocked", ", ".join(r["vector_id"] for r in V["per_vector"]
                               if r["scored"] and not r["eviassure_blocked"]) or "none"),
    ("falseBlockK", NC["k"]), ("falseBlockN", NC["n"]),
    ("fuzzCases", WF["n_cases"]),
    ("fuzzBlockedK", WF["semantics_changing_blocked"]["k"]),
    ("fuzzBlockedN", WF["semantics_changing_blocked"]["n"]),
    ("fuzzApprovedK", WF["semantics_preserving_approved"]["k"]),
    ("fuzzApprovedN", WF["semantics_preserving_approved"]["n"]),
    ("corpusProfiles", f"{corp['corpus']['total_profiles']:,}"),
    ("corpusClean", f"{corp['corpus']['clean_profiles']:,}"),
    ("corpusRecords", f"{corp['corpus']['total_trace_records']:,}"),
    ("corpusOvert", corp["corpus"]["overt_anomalies"]),
    ("corpusStealth", corp["corpus"]["stealth_anomalies"]),
    ("corpusClasses", INS["n_classes"]),
    ("insRecallK", INS["recall_overall"]), ("insRecallN", INS["n_anomalous"]),
    ("insRecallPct", f"{INS['recall_overall_pct']:.1f}"),
    ("insOvertK", sum(c["detected"] for c in ov)), ("insOvertN", sum(c["n"] for c in ov)),
    ("insStealthK", sum(c["detected"] for c in st)), ("insStealthN", sum(c["n"] for c in st)),
    ("insFPK", INS["clean_flagged"]), ("insFPN", INS["n_clean"]),
]

import re
n_tests = sum(len(re.findall(r"^def (test_\w+)", f.read_text(), re.M))
              for f in sorted((ROOT / "tests").glob("test_*.py"))
              if f.name != "test_docs_consistency.py")
rows.append(("testCount", n_tests))

# --- omission / witnessed-completeness macros ------------------------------
OM = sec["omission"]
OS = OM["summary"]
def om(sub):
    return next(v for k, v in OS.items() if sub.lower() in k.lower())
rows += [
    ("omVectors", OM["n_omission_vectors"]),
    ("omWtc", om("EviAssure + WTC")["k"]),
    ("omNoWtc", om("without witness")["k"]),
    ("omReceipts", om("Per-action receipts")["k"]),
    ("omChain", om("hash chaining")["k"]),
    ("omDsse", om("DSSE")["k"]),
    ("omTuf", om("TUF")["k"]),
    ("omControlOk", "yes" if all(OM["control_approved_by"].values()) else "NO"),
]

out = ["% GENERATED by scripts/write_security_macros.py -- do not edit by hand.",
       "% Bound to results/security_evaluation.json and results/corpus_evaluation.json.",
       f"% Generated {sec['timestamp']}"]
out += [f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in rows]
(ROOT / "docs" / "security_metrics.tex").write_text("\n".join(out) + "\n")
print(f"[+] docs/security_metrics.tex ({len(rows)} macros)")
